# Credits

This is heavily influenced or copied from https://github.com/pytorch/tutorials

# Autograd: automatic differentiation

Central to all neural networks in PyTorch is the ``autograd`` package.
Let’s first briefly visit this, and we will then go to training our first neural network.

The `autograd` package provides automatic differentiation for all operations on Tensors.
It is a define-by-run framework, which means that your backprop is defined by how your code is run, and that every single iteration can be different.

Let us see this in more simple terms with some examples.

## 1. Tensor

`torch.Tensor` is the central class of the package. Setting the attribute `.requires_grad` to `True` will make the tensor "record" all operations on it. When you finish your computation you can call `.backward()` and have all the gradients computed automatically. The gradient for this tensor will be accumulated into the `.grad` attribute.

![autograd.Variable](../static_files/autograd-variable.png)

There’s one more class which is very important for autograd implementation - a `Function`.

`Tensor` and `Function` are interconnected and build up an acyclic graph, that encodes a complete history of computation. Each tensor has a `.grad_fn` attribute that references a `Function` that has created the `Tensor` (except for Tensors created by the user - their `grad_fn` is `None`).

If you want to compute the derivatives, you can call `.backward()` on a Tensor. If `Tensor` is a scalar (i.e. it holds a one element data), you don’t need to specify any arguments to backward(), however if it has more elements, you need to specify a `gradient` argument that is a tensor of matching shape.

In [1]:
import torch

Create a tensor

In [2]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


Do a tensor operation:

In [3]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


`y` was created as a result of an operation, so it has a `grad_fn`.

In [6]:
print(y.grad_fn)

Do more operations on y

In [5]:
z = y * y * 3
out = z.mean()

print(z)
print(out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)


# Assignments

1. Create a Tensor that `requires_grad` of size (5, 5)
2. Sum the values in the Tensor

In [10]:
# 1
x1 = torch.rand(5, 5, requires_grad=True)
print(x1)
# 2
x2 = x1.sum()
print(x2)

tensor([[0.5347, 0.7670, 0.0682, 0.2866, 0.5993],
        [0.2737, 0.4399, 0.4266, 0.4077, 0.9861],
        [0.9523, 0.9546, 0.9384, 0.7479, 0.7197],
        [0.8589, 0.9030, 0.8126, 0.8780, 0.6244],
        [0.3099, 0.8645, 0.8671, 0.3957, 0.9820]], requires_grad=True)
tensor(16.5986, grad_fn=<SumBackward0>)


## 2. Gradients

Let’s backprop now. Because `out` contains a single scalar, `out.backward()` is equivalent to `out.backward(torch.tensor([1.0]))`

In [11]:
out.backward()

Print gradients d(out)/dx

In [12]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


You should have a matrix of `4.5`. Let’s denote the tensor `out` with $o$.

We have:
$o = \frac{1}{4}\sum_i z_i$, $z_i = 3(x_i+2)^2$ and $z_i\bigr\rvert_{x_i=1} = 27$.

Therefore, $\frac{\partial o}{\partial x_i} = \frac{3}{2}(x_i+2)$,
hence $\frac{\partial o}{\partial x_i}\bigr\rvert_{x_i=1} = \frac{9}{2} = 4.5$.

You can do many crazy things with autograd!

In [13]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([-374.5088, 1246.7753, -380.0201], grad_fn=<MulBackward0>)


In [14]:
gradients = torch.FloatTensor([0.1, 1.0, 0.0001])
y.backward(gradients)

print(x.grad)

tensor([2.0480e+02, 2.0480e+03, 2.0480e-01])


**Read later** \
*Documentation* \
`Tensor`: https://pytorch.org/docs/stable/tensors.html \
`Function`: http://pytorch.org/docs/autograd

# Assignments

1. Define a tensor and set `requires_grad` to `True`
3. Multiply the tensor by 2 and assign the result to a new python variable (i.e. `x = result`)
4. Sum the variable's elements and assign to a new python variable
5. Print the gradients of all the variables
6. Now perform a backward pass on the last variable (NOTE: for each new python variable that you define, call `.retain_grad()`)
7. Print all gradients again
  - what did you notice?

In [15]:
# 1
x1 = torch.randn(3, requires_grad=True)
x1.retain_grad()
print("Ex1: ", x1)
# 2
result = x1 * 2
x2 = result
x2.retain_grad()
print("Ex2: ",x2)
# 3
x3 = x2.sum()
x3.retain_grad()
print("Ex3: ",x3)
# 4
print("Ex4:")
print("\tgrad_ex1=", x1.grad)
print("\tgrad_ex2=", x2.grad)
print("\tgrad_ex3=", x3.grad)
# 5
x3.backward()
print("Ex5: Backward executed")
# 6
print("Ex6:")
print("\tgrad_ex1=", x1.grad)
print("\tgrad_ex2=", x2.grad)
print("\tgrad_ex3=", x3.grad)

Ex1:  tensor([ 0.7865,  1.3548, -0.1694], requires_grad=True)
Ex2:  tensor([ 1.5730,  2.7095, -0.3388], grad_fn=<MulBackward0>)
Ex3:  tensor(3.9438, grad_fn=<SumBackward0>)
Ex4:
	grad_ex1= None
	grad_ex2= None
	grad_ex3= None
Ex5: Backward executed
Ex6:
	grad_ex1= tensor([2., 2., 2.])
	grad_ex2= tensor([1., 1., 1.])
	grad_ex3= tensor(1.)


**Soltion**:

I notice that:
- At step 4 there are still no grads.
- When the backward pass is executed:
    - When we copy the result at step 2, it still points to the same tensor so it backpropagates to the first variable.
    - The gradients at x1 is 2 because in the next step every item was multiplied by 2.
    - The gradients at x2 is 1 because we summed them.
    - The gradients at x3 are just size 1, because when we sum the elements we go from size (3,1) to scalar.